name: smgs_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  model_viewer_plus: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/national-museum-web.jpg
    - assets/images/ho-chi-minh-museum-web.jpg
    - assets/images/ngoc-lu-web.jpg
    - assets/models/trong_dong_dong_son.glb
  fonts:
    - family: NotoSerif
      fonts:
        - asset: assets/fonts/NotoSerif.ttf
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans.ttf
